# WORKSPACE ---

[workspace]
  exclude = [
    "promo/*",
  ]

  members = [
    "crates/*",
    "examples/*",
  ]

[workspace.package]
  authors     = ["Dominik Kaspar"]
  version     = "0.0.12"
  edition     = "2021"
  license     = "MIT OR Apache-2.0"
  repository  = "https://github.com/bytestring-net/bevy-lunex"
  keywords    = ["ui", "layout", "bevy", "lunex", "bevy-lunex"]
  categories  = ["gui", "mathematics", "game-development"]
  description = "Supporting crate for bevy_lunex"
  readme      = "README.md"

[workspace.dependencies]
  ahash                = "^0.8.6"
  bevy                 = { version = "0.13.0", default-features = false, features = ["bevy_sprite", "bevy_render", "bevy_text", "bevy_gizmos"] }
  bevy_vector_shapes   = "0.7.0"
  colored              = "^2.0.4"
  mathio               = { version = "0.2.5", features = ["bevy"] }
  pathio               = { version = "0.2.3", features = ["bevy"] }

  bevy_lunex_core      = { path = "crates/bevy_lunex_core", version = "0.0.12"}
  bevy_lunex_ui        = { path = "crates/bevy_lunex_ui", version = "0.0.12"}
  bevy_lunex_utility   = { path = "crates/bevy_lunex_utility", version = "0.0.12"}


# BEVY LUNEX ---

[package]
  name                  = "bevy_lunex"
  description           = "Blazingly fast path based modular layout system built on top of Bevy ECS"
  authors.workspace     = true
  version.workspace     = true
  edition.workspace     = true
  license.workspace     = true
  repository.workspace  = true
  keywords.workspace    = true
  categories.workspace  = true
  readme.workspace      = true
  exclude = [
    "promo/*",
    ".gitignore",
    ".vscode",
  ]

[dependencies]
  bevy_lunex_core      = { workspace = true }
  bevy_lunex_ui        = { workspace = true }
  bevy_lunex_utility   = { workspace = true }
  mathio               = { workspace = true }

[dev-dependencies]
  bevy                 = { workspace = true, default-features = true, features = [ "dynamic_linking" ] }